name: Snake Game Generator

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *"  # Executa a cada 2 horas

jobs:
  generate_snake_game:
    runs-on: ubuntu-latest

    steps:
      # Baixa o repositório automaticamente
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera o jogo Snake com base nas contribuições e salva no local correto
      - name: Snake game generator from Github contributions
        uses: Sutil/snk@v01.00.02
        with:
          snake_color: "#00FF00"  # Altere para a cor desejada
          output: "./github-contribution-grid-snake-dark.svg"  # Define o nome e o caminho do arquivo

      # Atualiza o README.md com o caminho correto para a animação
      - name: Update README with Snake game animation
        run: |
          # Sobrescreve a linha existente no README para incluir a nova imagem
          echo "![Snake animation](./github-contribution-grid-snake-dark.svg)" > README.md
          
          # Configura o git para o commit
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          
          # Commit e push das mudanças
          git add README.md
          git commit -m "Atualiza README com a animação do jogo Snake"
          git push
